
export const SET_CAMPAIGN_NAME = 'SET_CAMPAIGN_NAME' 
export const SET_PLAYER_DATA = "SET_PLAYER_DATA"
export const SET_WORLD_DATA = "SET_WORLD_DATA"
export const SET_GOVERNMENT_DATA = "SET_GOVERNMENT_DATA"
export const SET_RELIGION = "SET_RELIGION"
export const SET_LANGUAGES = "SET_LANGUAGES"
export const SET_FACTION_ORGS = "SET_FACTION_ORGS"
export const SET_ACTS_CLIMAX = "SET_ACTS_CLIMAX"
export const SET_MAIN_GOAL = "SET_MAIN_GOAL"
export const SET_PILLAR = "SET_PILLAR"
export const SET_PATRON_DATA = "SET_PATRON_DATA"
export const SET_VILLAIN_DATA ="SET_VILLAIN_DATA"
export const SET_LOCAL_EVENTS = "SET_LOCAL_EVENTS"
export const SET_NPC_DATA = "SET_NPC_DATA"
export const SET_ENCOUNTERS = "SET_ENCOUNTERS"
export const SET_RANDOM_ENCOUNTERS = "SET_RANDOM_ENCOUNTERS"
export const SET_TWIST = "SET_TWIST"
export const SET_SIDE_QUESTS = "SET_SIDE_QUESTS"
export const SET_SETBACK = "SET_SETBACK"

export const SET_MONSTERS = "SET_MONSTERS"
export const SET_ROOMS = "SET_ROOMS"
export const SET_TREASURE_TYPE = "SET_TREASURE_TYPE"
export const SET_TREASURE_NUMBER = "SET_TREASURE_NUMBER"






