
export const SET_CAMPAIGN_NAME = 'SET_CAMPAIGN_NAME' 
export const SET_VILLIAN_NAME = "SET_VILLIAN_NAME"
export const SET_VILLIAN_TYPE = "SET_VILLIAN_TYPE"
export const SET_QUESTGIVER_NAME = "SET_QUESTGIVER_NAME"
export const SET_QUESTGIVER_TYPE = "SET_QUESTGIVER_TYPE"
export const SET_PLAYERDATA = "SET_PLAYERDATA"
export const SET_PILLAR = "SET_PILLAR"
export const SET_CLIMATE = "SET_CLIMATE"
export const SET_WORLD = "SET_WORLD"
export const SET_MEETING_PLACE = "SET_MEETING_PLACE"
export const SET_ACTS = "SET_ACTS"
export const SET_SIDE_QUESTS = "SET_SIDE_QUESTS"
export const SET_ROOMS = "SET_ROOMS"
export const SET_SETBACKS = "SET_SETBACKS"
export const SET_MONSTER_NUM = "SET_MONSTER_NUM"


