
export const SET_CAMPAIGN_NAME = 'SET_CAMPAIGN_NAME' 
export const SET_PLAYER_DATA = "SET_PLAYER_DATA"
export const SET_GOVERNMENT = "SET_GOVERNMENT"
export const SET_CURRENCY = "SET_CURRENCY"
export const SET_WORLD = "SET_WORLD"
export const SET_MAP_SCALE = "SET_MAP_SCALE"
export const SET_CHAR_MEETING = "SET_CHAR_MEETING"
export const SET_RELIGION = "SET_RELIGION"
export const SET_LANGUAGES = "SET_LANGUAGES"
export const SET_FACTION_ORGS = "SET_FACTION_ORGS"
export const SET_ACTS = "SET_ACTS"
export const SET_CLIMAX = "SET_CLIMAX"
export const SET_MAIN_GOAL = "SET_MAIN_GOAL"
export const SET_PILLAR = "SET_PILLAR"
export const SET_PATRON_NAME = "SET_PATRON_NAME"
// export const SET_NPC_NUMBER = "SET_NPC_NUMBER"
export const SET_VILLAIN_NAME ="SET_VILLAIN_NAME"
export const SET_LOCAL_EVENTS = "SET_LOCAL_EVENTS"
export const SET_RANDOM_ENOUNTER_NUMBER = "SET_RANDOM_ENCOUNTER_NUMBER"
export const SET_MONSTER_NUM = "SET_MONSTER_NUM"
export const SET_MONSTERS = "SET_MONSTERS"
export const SET_ROOMS = "SET_ROOMS"
export const SET_TREASURE_TYPE = "SET_TREASURE_TYPE"
export const SET_TREASURE_NUMBER = "SET_TREASURE_NUMBER"

// export const SET_SIDE_QUESTS = "SET_SIDE_QUESTS"
// export const SET_SETBACKS = "SET_SETBACKS"
// export const SET_DUNGEON_TYPE = "SET_DUNGEON_TYPE"



