import {
  faBeer,
  faGem,
  faCrown,
  faDragon,
  faHatWizard,
  faShieldAlt,
  faChessKnight,
  faAnchor,
  faAnkh,
  faArchway,
  faBalanceScaleLeft,
  faAtlas,
  faAtom,
  faBook,
  faBookDead,
  faBookMedical,
  faCross,
  faDiceD20,
  faDollarSign,
  faDotCircle,
  faDove,
  faDraftingCompass,
  faEye,
  faFire,
  faFish,
  faGlassCheers,
  faHollyBerry,
  faHorse,
  faHourglassHalf,
  faLandmark,
  faOm,
  faPallet,
  faPaw,
  faPenNib,
  faPlaceOfWorship,
  faSkull,
  faSpider,
  faStarOfDavid,
  faStar,
  faVihara,
} from "@fortawesome/free-solid-svg-icons";

export const icons = [
  { id: 1, icon: faBeer },
  { id: 2, icon: faGem },
  { id: 3, icon: faCrown },
  { id: 4, icon: faDragon },
  { id: 5, icon: faHatWizard },
  { id: 6, icon: faShieldAlt },
  { id: 7, icon: faChessKnight },
  { id: 8, icon: faAnchor },
  { id: 9, icon: faAnkh },
  { id: 10, icon: faArchway },
  { id: 11, icon: faBalanceScaleLeft },
  { id: 12, icon: faAtlas },
  { id: 13, icon: faAtom },
  { id: 14, icon: faBook },
  { id: 15, icon: faBookDead },
  { id: 16, icon: faBookMedical },
  { id: 17, icon: faCross },
  { id: 18, icon: faDiceD20 },
  { id: 19, icon: faDollarSign },
  { id: 20, icon: faDotCircle },
  { id: 21, icon: faDove },
  { id: 22, icon: faDraftingCompass },
  { id: 23, icon: faEye },
  { id: 24, icon: faFire },
  { id: 25, icon: faFish },
  { id: 26, icon: faGlassCheers },
  { id: 27, icon: faHollyBerry },
  { id: 28, icon: faHorse },
  { id: 29, icon: faHourglassHalf },
  { id: 30, icon: faLandmark },
  { id: 31, icon: faOm },
  { id: 32, icon: faPallet },
  { id: 33, icon: faPaw },
  { id: 34, icon: faPenNib },
  { id: 35, icon: faPlaceOfWorship },
  { id: 36, icon: faSkull },
  { id: 37, icon: faSpider },
  { id: 38, icon: faStarOfDavid },
  { id: 39, icon: faStar },
  { id: 40, icon: faVihara },
];
